#!/usr/bin/env python3
"""
Standalone script to plot power consumption data from CSV.
Usage: python3 plot_power.py <csv_file>
"""

import argparse
import sys
import csv
import matplotlib.pyplot as plt


def load_csv(filepath):
    """Load CSV data and return timestamps and power values."""
    timestamps = []
    power_values = []
    
    try:
        with open(filepath, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                timestamps.append(float(row['timestamp']))
                power_values.append(float(row['power']))
    except FileNotFoundError:
        print(f"Error: File not found: {filepath}")
        sys.exit(1)
    except KeyError as e:
        print(f"Error: Missing column in CSV: {e}")
        sys.exit(1)
    except ValueError as e:
        print(f"Error: Invalid data in CSV: {e}")
        sys.exit(1)
    
    return timestamps, power_values


def plot_power(timestamps, power_values, title="Power Consumption Over Time"):
    """Create a matplotlib plot of power vs time."""
    plt.figure(figsize=(12, 6))
    
    plt.plot(timestamps, power_values, 'b-', linewidth=1.5, label='Power (W)')
    
    plt.xlabel('Time (s)', fontsize=12)
    plt.ylabel('Power (W)', fontsize=12)
    plt.title(title, fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.legend(loc='upper right')
    
    # Add some statistics as text
    if power_values:
        avg_power = sum(power_values) / len(power_values)
        max_power = max(power_values)
        min_power = min(power_values)
        
        stats_text = f'Avg: {avg_power:.3f} W\nMax: {max_power:.3f} W\nMin: {min_power:.3f} W'
        plt.annotate(
            stats_text,
            xy=(0.02, 0.98),
            xycoords='axes fraction',
            verticalalignment='top',
            fontsize=10,
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5)
        )
    
    plt.tight_layout()
    plt.show()


def main():
    parser = argparse.ArgumentParser(
        description='Plot power consumption data from CSV file'
    )
    parser.add_argument(
        'csv_file',
        help='Path to the CSV file (generated by fake_power_node)'
    )
    parser.add_argument(
        '--title',
        default='Power Consumption Over Time',
        help='Plot title'
    )
    parser.add_argument(
        '--save',
        metavar='OUTPUT_FILE',
        help='Save plot to file instead of displaying (e.g., plot.png)'
    )
    
    args = parser.parse_args()
    
    print(f"Loading data from: {args.csv_file}")
    timestamps, power_values = load_csv(args.csv_file)
    print(f"Loaded {len(timestamps)} data points")
    
    if not timestamps:
        print("Error: No data points found in CSV")
        sys.exit(1)
    
    if args.save:
        plt.figure(figsize=(12, 6))
        plt.plot(timestamps, power_values, 'b-', linewidth=1.5, label='Power (W)')
        plt.xlabel('Time (s)', fontsize=12)
        plt.ylabel('Power (W)', fontsize=12)
        plt.title(args.title, fontsize=14)
        plt.grid(True, alpha=0.3)
        plt.legend(loc='upper right')
        plt.tight_layout()
        plt.savefig(args.save, dpi=150)
        print(f"Plot saved to: {args.save}")
    else:
        plot_power(timestamps, power_values, args.title)


if __name__ == '__main__':
    main()
